name: workoutapi
services:
  db:
    environment:
      POSTGRES_DB: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
    image: postgres:11-alpine
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
networks:
  default:
    name: workoutapi_default
